//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyGiangDay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiangVien
    {
        public int MaGV { get; set; }
        public string HotenGiangVien { get; set; }
        public Nullable<System.DateTime> NgayThangNamSinh { get; set; }
        public string DanToc { get; set; }
        public string QueQuan { get; set; }
        public string QuocTich { get; set; }
        public Nullable<int> CMND { get; set; }
        public Nullable<int> DienThoai { get; set; }
        public string Email { get; set; }
    }
}
